apiVersion: apps/v1
kind: Deployment
metadata:
  name: aad-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      run: aad-provider
  template:
    metadata:
      labels:
        run: aad-provider
    spec:
      containers:
        - image: sozercan/aad-provider:v0.0.1
          imagePullPolicy: Always
          name: aad-provider
          ports:
            - containerPort: 8090
              protocol: TCP
          env:
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: aad-provider-secret
                  key: tenantID
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: aad-provider-secret
                  key: clientID
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: aad-provider-secret
                  key: clientSecret
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
